### ISSUE TITLE
XLD windows login task leaks password

### ISSUE THREAD

**Issue by MarkRx** [xebialabs-community/xld-openshift-plugin#11]
Windows by default has echo on in batch scripts. As a result the oc login command is logged with the password.

**Comment by px-djozis** [comment]
Simple fix would be to put this at the start of each script if running on Windows: @echo off

**Comment by jdewinne** [comment]
Thanks. I've fixed it in version [6.4.1](https://github.com/xebialabs-community/xld-openshift-plugin/releases/tag/v6.4.1)
