### ISSUE TITLE
XLD windows login fails

### ISSUE THREAD

**Issue by MarkRx** [xebialabs-community/xld-openshift-plugin#12]
oc-login-deployed.ftl uses single quotes around the password (-p) parameter. Windows needs to use double quotes. Linux should continue to use single quotes to prevent script injection.

> Uploading file checkOC.bat to working directory.
> Executing C:\windows\TEMP\ot-20170109T142703194\generic_plugin.tmp\checkOC.bat on host Infrastructure/sandbox/openshift/tax/oc-host-henrietta
> C:\windows\TEMP\ot-20170109T142703194\generic_plugin.tmp>set KUBECONFIG=./config
> C:\windows\TEMP\ot-20170109T142703194\generic_plugin.tmp>echo off
> Login failed (401 Unauthorized)
> C:\windows\TEMP\ot-20170109T142703194\generic_plugin.tmp>N:\xebialabs\xld\server\oc\ose-clients-3.2.1.13/oc status
> error: No configuration file found, please login or point to an existing file:
> 1. Via the command-line flag --config
> 2. Via the KUBECONFIG environment variable
> 3. In your home directory as ~/.kube/config
> To view or setup config directly use the 'config' command.
> C:\windows\TEMP\ot-20170109T142703194\generic_plugin.tmp>N:\xebialabs\xld\server\oc\ose-clients-3.2.1.13/oc logout
> error: No configuration file found, please login or point to an existing file:
> 1. Via the command-line flag --config
> 2. Via the KUBECONFIG environment variable
> 3. In your home directory as ~/.kube/config
> To view or setup config directly use the 'config' command.
> Execution failed with return code 1

**Comment by jdewinne** [comment]
Thanks. I've changed it in version [6.4.1](https://github.com/xebialabs-community/xld-openshift-plugin/releases/tag/v6.4.1)
