### ISSUE TITLE
XLD Windows errors are ignored

### ISSUE THREAD

**Issue by px-djozis** [xebialabs-community/xld-openshift-plugin#13]
If an error occurs during a batch script, it does not fail the step:
```
C:\windows\TEMP\ot-20170109T143257285\working.directory.tmp>N:/xebialabs/xld/server/oc/ose-clients-3.2.1.13/oc project sandbox-tax-filing
error: You are not a member of project "sandbox-tax-filing".
Your projects are:
* dvs3-payroll-ext
...
```

You can fix this by appending the following to lines that should propagate errors:
`|| exit /b 1`

**Comment by jdewinne** [comment]
Thanks. I've fixed it in version [6.4.1](https://github.com/xebialabs-community/xld-openshift-plugin/releases/tag/v6.4.1)
