### ISSUE TITLE
openshift.Resource MODIFY does not work

### ISSUE THREAD

**Issue by MarkRx** [xebialabs-community/xld-openshift-plugin#5]
The rule for modifying an existing openshift resource does not work.  Right now it defaults to running the create shell script which runs oc create. As a result openshift responds with an error indicating that the resource already exists.

> create new resource
> Error from server: error when creating "/tmp/ot-20161230T102131383/working.directory.tmp/xld.6266/helloworld-svc.json": services "helloworld-svc" already exists
> Execution failed with exit code 1

**Comment by jdewinne** [comment]
Hi Mark,

I just fixed this issue in version 6.2.1.

Regards,
Joris
