### ISSUE TITLE
Plugin does not support Windows oc client

### ISSUE THREAD

**Issue by MarkRx** [xebialabs-community/xld-openshift-plugin#6]
The openshift oc client comes in a windows variant. It appears that the plugin does not support this. Supporting the windows oc client would allow for using a master windows machine to run oc commands instead of having to setup linux machines with the sole purpose of running oc commands.

**Comment by jdewinne** [comment]
Thanks for bringing this up. I've added the corresponding batch scripts in version [6.3.0](https://github.com/xebialabs-community/xld-openshift-plugin/releases/tag/v6.3.0)
