### ISSUE TITLE
openshift.Resource does not perform token substituion on json/yml files by default

### ISSUE THREAD

**Issue by MarkRx** [xebialabs-community/xld-openshift-plugin#7]
This is inconvenient as resources are specified in yml or json format.

It could be done using the following in synthetic.xml:

`<property name="textFileNamesRegex" hidden="true" default=".+\.(cfg | conf | config | ini | properties | props | txt | asp | aspx | htm | html | jsf | jsp | xht | xhtml | sql | xml | xsd | xsl | xslt | json | yml | yaml )" />`

I don't know why XLD does not support this on deployables by default. It shouldn't be a problem for json files as the string "{{" is not valid json (though "}}" is).

**Comment by jdewinne** [comment]
Fixed this in v6.2.2. Thanks for reporting.
