### ISSUE TITLE
Plugin will not support concurrent deployments

### ISSUE THREAD

**Issue by MarkRx** [xebialabs-community/xld-openshift-plugin#8]
Looking at the shell scripts I see that each step runs an oc login and an oc logout command. If multiple deployments occur at the same time one might log another one out before it is ready. This will result in seemingly random failed deployments.

**Comment by jdewinne** [comment]
Hi Mark,

Are you sure this is the case. I think because each step in XLD will use its own `KUBECONFIG` file, I would assume the sessions to be separated.

Regards,
Joris

**Comment by MarkRx** [comment]
Ah I see. What directory does overthere operate in?

> export KUBECONFIG=./config

**Comment by MarkRx** [comment]
Yes it does operate in a temp dir that is unique each time. Looks like this isn't an issue after all.
